In [1]:
import numpy as np

In [7]:
a=np.arange(0,10,2)

In [8]:
a

array([0, 2, 4, 6, 8])

In [9]:
a[1]+3

5

In [10]:
b=[4,6,8,78]

In [11]:
b[1]+5

11

In [12]:
c=np.array([[4,8,79],[45,71,23]])

In [13]:
c

array([[ 4,  8, 79],
       [45, 71, 23]])

In [14]:
d=np.array([[8,45,11],[56,23,10]])

In [15]:
d

array([[ 8, 45, 11],
       [56, 23, 10]])

In [16]:
k=np.hstack((c,d))

In [17]:
k

array([[ 4,  8, 79,  8, 45, 11],
       [45, 71, 23, 56, 23, 10]])

In [18]:
np.concatenate((c,d), axis=1)

array([[ 4,  8, 79,  8, 45, 11],
       [45, 71, 23, 56, 23, 10]])

In [19]:
np.concatenate((c,d), axis=0)

array([[ 4,  8, 79],
       [45, 71, 23],
       [ 8, 45, 11],
       [56, 23, 10]])

In [20]:
p=np.vstack((c,d))

In [21]:
p

array([[ 4,  8, 79],
       [45, 71, 23],
       [ 8, 45, 11],
       [56, 23, 10]])

In [56]:
p[0:,0:2]

array([[ 4,  8],
       [45, 71],
       [ 8, 45],
       [56, 23]])

In [23]:
p.dtype

dtype('int32')

In [24]:
np.zeros((3,3), dtype='int32')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [25]:
p.shape

(4, 3)

In [26]:
np.sum((c,d),axis=1)

array([[ 49,  79, 102],
       [ 64,  68,  21]])

In [34]:
c.argmax(axis=1)

array([2, 2], dtype=int64)

In [40]:
d.argmax(axis=0)

array([1, 0, 0], dtype=int64)

In [47]:
pk=np.array([12,45,98])
kl=np.array([13,79,54])

In [55]:
pk+10

array([ 22,  55, 108])

In [57]:
p=np.sqrt(c)

In [58]:
p

array([[2.        , 2.82842712, 4.79583152],
       [6.70820393, 8.42614977, 8.88819442]])

In [59]:
p

array([[2.        , 2.82842712, 4.79583152],
       [6.70820393, 8.42614977, 8.88819442]])

In [4]:
import pandas as pd
kp=pd.DataFrame([[4,7,10], [6,8,2], [1,3,4], [2,10,5]])

In [8]:
kp.loc[1:4]

0   1  2
1  6   8  2
2  1   3  4
3  2  10  5